require_relative "test_helper"
require "json"
require "net/http"
require "open3"
require "rbconfig"
require "timeout"
require "tmpdir"
require "fileutils"

# The two boot scripts, run for real against a real Puma: the one the packers
# copy into a bundle, and the one the generator writes to bin/desktop-boot.
#
# What they must not do is read the app's config/puma.rb. Puma loads that file
# on its own whenever the working directory has one, and it describes how the
# app is deployed, not how a desktop app serves itself. Rails 7.0 and 7.1
# generate one with `pidfile ENV.fetch("PIDFILE") { "tmp/pids/server.pid" }`,
# so every app generated by those versions died at boot inside its read-only
# bundle, writing a pidfile to a directory that is not there. Rails 7.2 and 8
# only set a pidfile when PIDFILE is set, which is why it went unnoticed.
class BootScriptTest < Minitest::Test
  REPOSITORY = File.expand_path("../..", __dir__)

  SCRIPTS = {
    "the packaged boot.rb" => File.join(REPOSITORY, "packaging", "templates", "boot.rb"),
    "the generated bin/desktop-boot" => File.expand_path(
      "../lib/generators/desktop_rails/install/templates/desktop-boot.tt", __dir__
    )
  }.freeze

  def setup
    super
    @tmp = Dir.mktmpdir("desktop-rails-boot")
    @app = File.join(@tmp, "app")
    FileUtils.mkdir_p(File.join(@app, "config"))
    File.write(File.join(@app, "config.ru"), <<~RUBY)
      run ->(_env) { [ 200, { "content-type" => "text/plain" }, [ "served" ] ] }
    RUBY
    # What `rails _7.1.6_ new` writes, less the comments. tmp/pids does not
    # exist here, as it does not in a bundle.
    File.write(File.join(@app, "config", "puma.rb"), <<~RUBY)
      threads 5, 5
      port ENV.fetch("PORT") { 3000 }
      environment ENV.fetch("RAILS_ENV") { "development" }
      pidfile ENV.fetch("PIDFILE") { "tmp/pids/server.pid" }
      plugin :tmp_restart
    RUBY
  end

  def teardown
    FileUtils.rm_rf(@tmp)
    super
  end

  SCRIPTS.each do |label, source|
    slug = label.gsub(/\W+/, "_")

    define_method("test_#{slug}_serves_without_reading_config_puma_rb") do
      script = File.join(@app, "boot.rb")
      FileUtils.cp(source, script)

      output = boot(script) do |url|
        response = Net::HTTP.get_response(URI("#{url}/"))
        assert_equal "200", response.code
        assert_equal "served", response.body
      end

      refute File.exist?(File.join(@app, "tmp", "pids", "server.pid")),
             "the app's own pidfile setting was applied:\n#{output}"
    end
  end

  private

  # Runs the script the way a bundle's launcher does: from the app directory,
  # which is where Puma looks for config/puma.rb, with stdin held open as the
  # exit signal and the first line of stdout read as the handshake.
  def boot(script)
    env = { "DESKTOP_DATA_DIR" => File.join(@tmp, "data"), "DESKTOP_RAILS_ENV" => "desktop" }
    Open3.popen3(env, RbConfig.ruby, script, chdir: @app) do |stdin, stdout, stderr, thread|
      errors = Thread.new { stderr.read }
      line = Timeout.timeout(60) { stdout.gets }
      if line.nil?
        stdin.close
        thread.join
        flunk "#{File.basename(script)} exited without a handshake:\n#{errors.value}"
      end

      yield JSON.parse(line).fetch("url")

      stdin.close
      assert Timeout.timeout(30) { thread.value }.success?, "the server did not exit cleanly on EOF"
      errors.value
    ensure
      Process.kill(:KILL, thread.pid) if thread&.alive?
    end
  end
end
